name : CI 

on:
  push: 
    branches : [main]
  pull_request:
    branches : [main]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name : Checkout repository
      uses: actions/checkout@v3

    - name : Setup Docker BuildX
      uses: docker/setup-buildx-action@v3

    - name : Test Dockerfile 
      run: |
        set -x 
        if [ -f Dockerfile ]; then
          echo "Dockerfile found"
        else
          echo "Dockerfile not found"
        fi


    - name : Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Validate YAML files
      run: |
        echo "ğŸ” Validating YAML files..."
        find . -name "*.yaml" -o -name "*.yml" | xargs -r yamllint -d "{extends: relaxed, rules: {line-length: disable}}"

    - name : Build Docker image
      run: |
        echo "ğŸ”§ Building Docker image..."
        docker build -t praveensubramanyam/genai_pat7:fastapi .
    
    - name : Push Docker image
      run: |
        echo "ğŸš€ Pushing Docker image to DockerHub..."
        docker push praveensubramanyam/genai_pat7:fastapi

